# Not to do list API
@baseUrl = http://localhost:8000/api/v1/tasks

### POST the task list
POST {{baseUrl}}
Content-Type: application/json

{
    
    "task":"sleeping",
    "hr":10,
    "type":"bad"

}

### GET the task list
GET {{baseUrl}}

### Update the task list
PATCH {{baseUrl}}
Content-Type: application/json


{
    "_id":"6a0ed63363ba0dd7699296f7",
    "hr": 8,
    "type": "bad"
}

### Delete the task list
DELETE {{baseUrl}}/6a0ed63363ba0dd7699296f7