# Not to do list API
@baseUrl = http://localhost:8000/api/v1/tasks

### POST the task list
POST {{baseUrl}}
Content-Type: application/json

{
    "id":,
    "task":"sleeping",
    "hr":7,
    "type":"entry"
}

### GET the task list
GET {{baseUrl}}

### Update the task list
PATCH {{baseUrl}}
Content-Type: application/json


{
    "id":2,
    "type":"bad"
}

### Delete the task list
DELETE {{baseUrl}}/2